#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""llmwiki build_index — 从 frontmatter 派生 wiki 内全部汇总面(W-IDX-1,仅 Python 标准库)。

一切汇总皆派生(单源原则,移植自参考实例 newpj4 tools/build_index.py,去 domain 化):
  - wiki/index.md              主索引:综合/概念/实体三区,每行 `- [[slug]] — 摘要`,
                               摘要 = 各页 frontmatter `description:` 截断 140 字;
                               徽章 emoji 由 config `facets[].badges` 注入
                               (cross 徽章 = 页 tags 含 `cross-<facet.key>`);
  - wiki/index-sources-*.md    来源分片:config facets 中首个 `shard_index: true` 的
                               facet 按值分片 `index-sources-<value>.md`;
                               无此 facet 时输出单一 `wiki/index-sources.md`;
  - wiki/contradictions.md     全库 `> ⚠️` 标记聚合(W-ING-3 真矛盾的机器汇总面),
                               逐条带来源 wikilink。
  - wiki/backlinks.md          反链索引(W-IDX-4):每页被哪些页引用,经 lib/wikigraph 解析
                               全库 wikilink 派生;每行 `- [[被引页]] ← [[引用页]], …`。

写入边界(W-ARCH-2 例外条款):本工具只写上述 wiki 内派生物;每个生成区带
`<!-- generated … -->` 标记,手编无效——改对应页 frontmatter `description:` 后重跑。

用法:python3 tools/build_index.py [--root DIR] [--json]
exit:0 成功 / 1 运行失败 / 2 配置与用法错误
"""
from __future__ import annotations

import argparse
import datetime
import json
import sys
from pathlib import Path

_TOOLS = Path(__file__).resolve().parent
for _p in (str(_TOOLS), str(_TOOLS / "lib")):
    if _p not in sys.path:
        sys.path.insert(0, _p)
import fm  # noqa: E402  (钉死 API:tools/lib/fm.py)
import wikigraph  # noqa: E402  (图谱/派生物判定单源,W-IDX-4)

INDEX_DESC_LEN = 140     # 主索引每行摘要截断长度(字符):检索线索,不是正文
AGG_KINDS = [("syntheses", "综合 / Syntheses"),
             ("concepts", "概念 / Concepts"),
             ("entities", "实体 / Entities")]
GEN_MARK_PREFIX = "<!-- generated"


def _gen_mark() -> str:
    return "<!-- generated by tools/build_index.py; 手编无效,改 frontmatter description 后重跑 -->"


# ---------------------------------------------------------------- 小工具

def _s(meta: dict, key: str) -> str:
    """meta 标量取值(list 时取首项),恒返回 str。"""
    v = meta.get(key, "")
    if isinstance(v, list):
        v = v[0] if v else ""
    return str(v).strip()


def _tags(meta: dict) -> list:
    v = meta.get("tags", [])
    if isinstance(v, list):
        return [str(t).strip() for t in v]
    v = str(v).strip()
    if v.startswith("[") and v.endswith("]"):
        v = v[1:-1]
    return [t.strip() for t in v.split(",") if t.strip()]


def one_liner(meta: dict) -> str:
    d = " ".join(_s(meta, "description").split())
    if len(d) > INDEX_DESC_LEN:
        d = d[:INDEX_DESC_LEN].rstrip() + "…"
    return d


def badges_for(meta: dict, facets: list) -> str:
    """按 config facets[].badges 注入徽章:cross 徽章 = tags 含 cross-<key>;
    其余按页 frontmatter <key>: <value>(或 tags 含 <key>-<value>)命中 badges[value]。"""
    out = []
    tags = _tags(meta)
    for f in facets:
        badges = f.get("badges") or {}
        if not badges:
            continue
        key = f.get("key", "")
        if "cross" in badges and ("cross-%s" % key) in tags:
            out.append(badges["cross"])
            continue
        val = _s(meta, key)
        if not val:
            for v in f.get("values", []):
                if ("%s-%s" % (key, v)) in tags:
                    val = v
                    break
        if val and val in badges:
            out.append(badges[val])
    return "".join(out)


def badge_legend(facets: list) -> str:
    """索引头部徽章图例,如 `(🔀=cross-vendor,🟢=openai)`;无徽章返回空串。"""
    parts = []
    for f in facets:
        key = f.get("key", "")
        for bk, emoji in (f.get("badges") or {}).items():
            label = ("cross-%s" % key) if bk == "cross" else bk
            parts.append("%s=%s" % (emoji, label))
    return "(%s)" % ",".join(parts) if parts else ""


def _preserved_created(path: Path, today: str) -> str:
    """派生页保留既有 created:(首次生成才用今天),避免无谓 diff。"""
    if path.is_file():
        try:
            meta, _ = fm.parse_frontmatter(path.read_text(encoding="utf-8"))
            c = str(meta.get("created", "")).strip()
            if c and c != "YYYY-MM-DD":
                return c
        except (OSError, UnicodeDecodeError):
            pass
    return today


# ---------------------------------------------------------------- 派生数据(lint_wiki 复用,勿改签名)

def agg_lines(wiki: Path, cfg: dict) -> dict:
    """三区条目行:{kind: ["- [[kind/slug]] — 徽章+摘要", ...]}。"""
    facets = cfg.get("facets", [])
    out = {}
    for kind, _label in AGG_KINDS:
        lines = []
        d = wiki / kind
        if d.is_dir():
            for f in sorted(d.glob("*.md")):
                meta, _ = fm.parse_frontmatter(f.read_text(encoding="utf-8"))
                lines.append("- [[%s/%s]] — %s%s"
                             % (kind, f.stem, badges_for(meta, facets), one_liner(meta)))
        out[kind] = lines
    return out


def query_lines(wiki: Path) -> list:
    d = wiki / "queries"
    if not d.is_dir():
        return []
    out = []
    for f in sorted(d.glob("*.md")):
        meta, _ = fm.parse_frontmatter(f.read_text(encoding="utf-8"))
        out.append("- [[queries/%s]] — %s" % (f.stem, one_liner(meta)))
    return out


def shard_facet(cfg: dict):
    """config facets 中首个 shard_index=true 的 facet(无则 None)。"""
    for f in cfg.get("facets", []):
        if f.get("shard_index"):
            return f
    return None


def source_shards(wiki: Path, cfg: dict):
    """来源条目行分桶。

    返回 (facet_or_None, {bucket: [line, ...]}):
      - 有 shard facet:bucket = 各页 frontmatter <key> 取值(先建 facet.values 空桶,
        未声明取值动态成桶,缺失归 "unfiled" 桶——lint W-PAGE-4 会另行报缺字段);
      - 无 shard facet:单桶 {"": [...]} → 输出单一 index-sources.md。
    行内摘要 = 源页 frontmatter description(W-IDX-1 唯一事实源),倒序按日期。
    """
    facet = shard_facet(cfg)
    facets = cfg.get("facets", [])
    entries = []   # (date, slug, bucket, line)
    d = wiki / "sources"
    if d.is_dir():
        for f in sorted(d.glob("*.md")):
            meta, _ = fm.parse_frontmatter(f.read_text(encoding="utf-8"))
            date = _s(meta, "date_published") or _s(meta, "date_ingested")
            kind = _s(meta, "source_kind")
            if facet is None:
                bucket = ""
                badge = badges_for(meta, facets)
            else:
                bucket = _s(meta, facet["key"]) or "unfiled"
                badge = ""   # 分片本身即分面,行内不再重复徽章
            line = "- [[sources/%s]] — %s%s (%s, %s)" % (
                f.stem, badge, one_liner(meta), kind or "?", date or "?")
            entries.append((date, f.stem, bucket, line))
    entries.sort(key=lambda e: (e[0], e[1]), reverse=True)
    shards = {}
    if facet is not None:
        for v in facet.get("values", []):
            shards[v] = []
    else:
        shards[""] = []
    for _date, _slug, bucket, line in entries:
        shards.setdefault(bucket, []).append(line)
    return facet, shards


def backlink_lines(wiki: Path) -> list:
    """反链条目行:`- [[被引页]] ← [[引用页1]], …`(W-IDX-4;lint_wiki 复用,勿改签名)。

    经 lib/wikigraph 从全库 wikilink 派生(边表 → 反链),按被引页 slug 升序、来源页升序去重;
    派生物/log 的出链不入图,故不会把孤儿页救活;无入链的页不出现在此(那才是孤儿)。"""
    bl = wikigraph.backlinks(wikigraph.build_graph(wiki))
    return ["- [[%s]] ← %s" % (to, ", ".join("[[%s]]" % f for f in froms))
            for to, froms in bl.items()]


def contradiction_lines(wiki: Path) -> list:
    """全库 `> ⚠️` blockquote 聚合行:`- [[rel]] — 文本(截 300 字)`(log/派生物豁免)。"""
    out = []
    for f in sorted(wiki.glob("**/*.md")):
        rel = f.relative_to(wiki).as_posix()[:-3]
        if rel == "log" or wikigraph.is_derived(rel):  # log 流水账 + 派生物(含 backlinks)豁免
            continue
        lines = f.read_text(encoding="utf-8").split("\n")
        i = 0
        while i < len(lines):
            if lines[i].lstrip().startswith(">") and "⚠️" in lines[i]:
                block = []
                while i < len(lines) and lines[i].lstrip().startswith(">"):
                    block.append(lines[i].lstrip())
                    i += 1
                out.append("- [[%s]] — %s" % (rel, " ".join(block)[:300]))
            else:
                i += 1
    return out


def lineage_lines(wiki: Path) -> list:
    """全库 supersession 演进链聚合行(W-ING-5;log/派生物豁免,与 contradiction_lines 同口径)。

    数据源 = 聚合页 frontmatter 的 `supersedes:` / `superseded_by:`(两侧同一条边只收一次)。
    行格式**刻意不以 `- [[` 起头**:contradictions.md 的 ⚠️ 条目区按该前缀被机检计数,
    演进链混进去会污染那个口径。不可解析的 slug 渲染成反引号纯文本(不产生断链 error)。
    """
    page_set = {p.relative_to(wiki).as_posix()[:-3] for p in sorted(wiki.rglob("*.md"))}
    pairs = set()
    for f in sorted(wiki.glob("**/*.md")):
        rel = f.relative_to(wiki).as_posix()[:-3]
        if rel == "log" or wikigraph.is_derived(rel):
            continue
        meta, _body = fm.parse_frontmatter(f.read_text(encoding="utf-8"))
        for t in wikigraph.fm_slugs(meta, "supersedes"):          # 本页取代 t:t 旧 → rel 新
            pairs.add((wikigraph.resolve_slug(t, page_set) or t, rel))
        for t in wikigraph.fm_slugs(meta, "superseded_by"):       # 本页被 t 取代:rel 旧 → t 新
            pairs.add((rel, wikigraph.resolve_slug(t, page_set) or t))
    def _ref(slug):
        return "[[%s]]" % slug if slug in page_set else "`%s`(未解析)" % slug
    return ["- 旧 %s → 新 %s" % (_ref(old), _ref(new))
            for old, new in sorted(pairs)]


# ---------------------------------------------------------------- 渲染

def render_shard(bucket: str, lines: list, created: str, today: str) -> str:
    label = bucket if bucket else "全部"
    return """---
title: 来源目录分片 · %s
description: "%s 来源目录(机器派生):按日期倒序一行一源。找某篇来源时 grep 本页;勿整读。"
type: overview
created: %s
updated: %s
tags: [meta, index]
status: mature
---

# 来源 / Sources · %s (%d)

> 由 `tools/build_index.py` 从 `wiki/sources/` frontmatter 派生(倒序按日期)。**勿整读**——
> 用 `grep -i '关键词'` 定位;机器查询走 `site/agent/sources.jsonl`。

%s
%s
""" % (label, label, created, today, label, len(lines), _gen_mark(),
       "\n".join(lines) if lines else "- (暂无来源)")


def render_index(cfg: dict, agg: dict, facet, shards: dict, qlines: list) -> str:
    legend = badge_legend(cfg.get("facets", []))
    n_src = sum(len(v) for v in shards.values())
    parts = ["""# Index 目录

> 全站内容目录。每条:`- [[slug]] — 一句话摘要`。**综合/概念/实体三区由
> `tools/build_index.py` 从各页 frontmatter `description:` 派生**%s,
> 手工编辑会被覆盖;要改摘要请改对应页面的 `description:` 后重跑派生。
> 本文件勿整读,用 grep 定位(配方见 [[_map]])。

%s

## 综述 / Overview

- [[_map]] — agent 路由页(第一读)
- [[overview]] — 顶层综述:大问题与主题地图
- [[followups]] — 待跟进:待读资源/待验证/未解问题/待晋升
- [[contradictions]] — 未决矛盾/张力一览(⚠️ 派生汇总)
""" % (legend, _gen_mark())]
    for kind, label in AGG_KINDS:
        lines = agg[kind]
        parts.append("## %s (%d)\n\n%s\n" % (label, len(lines), "\n".join(lines)))
    src_sec = ["## 来源 / Sources (%d)\n" % n_src]
    if facet is not None:
        src_sec.append("> 已按 %s 分片,**勿在此平铺**:" % facet["key"])
        for bucket in shards:
            src_sec.append("- [[index-sources-%s]] — %s 源目录 (%d 条)"
                           % (bucket, bucket, len(shards[bucket])))
    else:
        src_sec.append("- [[index-sources]] — 来源目录 (%d 条)" % n_src)
    src_sec.append("- 机器查询:`site/agent/sources.jsonl`(每行一条,含 token 预估;grep 单行命中)")
    parts.append("\n".join(src_sec) + "\n")
    parts.append("## 已存档查询 / Filed Queries (%d)\n%s"
                 % (len(qlines), ("\n" + "\n".join(qlines) + "\n" if qlines else "")))
    return "\n".join(parts)


def render_backlinks(lines: list, created: str, today: str) -> str:
    return """---
title: 反链索引 / Backlinks
description: "查『谁引用了 X』或找孤儿线索时读本页:每页被哪些页引用的机器派生反链,逐条 wikilink 可溯源。"
type: overview
created: %s
updated: %s
tags: [meta, index]
---

# 反链索引 / Backlinks (%d)

> 派生页(W-IDX-4):由 `tools/build_index.py` 从全库 wikilink(经 `lib/wikigraph` 解析)派生,
> 每行 `- [[被引页]] ← [[引用页]], …`。**手编即被下次 build 覆盖**;要改引用关系改对应页正文。
> 本页是派生物,其链接不计有机入链(不会把孤儿页救活);无入链的页不出现在此——那才是孤儿(见 lint)。

%s
%s
""" % (created, today, len(lines), _gen_mark(),
       "\n".join(lines) if lines else "- (暂无反链)")


def render_contradictions(entries: list, created: str, today: str,
                          lineage=()) -> str:
    return """---
title: 未决矛盾/张力一览
description: "全库 ⚠️ 标记的机器派生汇总:查『当前有哪些未决矛盾/口径张力』读本页;逐条溯源点 wikilink;附 supersession 演进链。"
type: overview
created: %s
updated: %s
tags: [meta, contradictions]
---

# 未决矛盾 / 张力一览 (%d)

> 派生页(W-IDX-1):由 `tools/build_index.py` 从全库 `> ⚠️` 标记派生,**手编即被下次 build 覆盖**。
> 裁决一条矛盾 = 回原页修改/移除 ⚠️ 标记(三分:演进/对比/真矛盾,W-ING-3),再重跑派生。

%s
%s

## 演进链 / Lineage (%d)

> 由 frontmatter `supersedes:` / `superseded_by:` 派生(W-ING-5):**演进 ≠ 矛盾**——被取代的旧结论
> 不进上面的 ⚠️ 区,只在此登记 lineage。查「这页还是最新的吗」看本节;命中旧页须跟到后继页。

%s
""" % (created, today, len(entries), _gen_mark(),
       "\n".join(entries) if entries else "- (暂无 ⚠️ 标记)",
       len(lineage), "\n".join(lineage) if lineage else "- (暂无演进链)")


# ---------------------------------------------------------------- 主流程

def _write_if_changed(path: Path, content: str) -> bool:
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def build(root: Path, cfg: dict) -> dict:
    """派生并落盘;返回统计(供 --json 与调用方)。"""
    wiki = root / "wiki"
    today = datetime.date.today().isoformat()
    agg = agg_lines(wiki, cfg)
    qlines = query_lines(wiki)
    facet, shards = source_shards(wiki, cfg)
    entries = contradiction_lines(wiki)

    written, unchanged = [], []

    def emit(path: Path, content: str):
        (written if _write_if_changed(path, content) else unchanged).append(
            path.relative_to(root).as_posix())

    expected_shards = set()
    for bucket, lines in shards.items():
        name = "index-sources-%s.md" % bucket if bucket else "index-sources.md"
        expected_shards.add(name)
        p = wiki / name
        emit(p, render_shard(bucket, lines, _preserved_created(p, today), today))
    # 清理不再对应任何分桶的旧分片(改 facet values 后的残留)
    removed = []
    for old in sorted(wiki.glob("index-sources*.md")):
        if old.name not in expected_shards:
            old.unlink()
            removed.append(old.relative_to(root).as_posix())

    emit(wiki / "index.md", render_index(cfg, agg, facet, shards, qlines))
    p = wiki / "contradictions.md"
    lin = lineage_lines(wiki)
    emit(p, render_contradictions(entries, _preserved_created(p, today), today, lin))
    bl_lines = backlink_lines(wiki)
    p_bl = wiki / "backlinks.md"
    emit(p_bl, render_backlinks(bl_lines, _preserved_created(p_bl, today), today))

    return {
        "agg_entries": sum(len(v) for v in agg.values()),
        "sources": sum(len(v) for v in shards.values()),
        "shards": {(b or "(single)"): len(v) for b, v in shards.items()},
        "shard_facet": facet["key"] if facet else None,
        "queries": len(qlines),
        "contradictions": len(entries),
        "lineage": len(lin),
        "backlinks": len(bl_lines),
        "written": written, "unchanged": unchanged, "removed": removed,
    }


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description="从 frontmatter 派生 wiki/index*.md 与 wiki/contradictions.md(W-IDX-1)")
    ap.add_argument("--root", default=".", help="实例根(含 wiki.config.json;默认 cwd)")
    ap.add_argument("--json", action="store_true", help="机器输出(结构化统计)")
    args = ap.parse_args(argv)

    root = Path(args.root).resolve()
    try:
        cfg = fm.load_config(root)
    except fm.ConfigError as e:
        print("配置错误: %s" % e, file=sys.stderr)
        return 2
    if not (root / "wiki").is_dir():
        print("配置错误: %s/wiki 不存在(--root 应指向实例根)" % root, file=sys.stderr)
        return 2

    try:
        stats = build(root, cfg)
    except (OSError, UnicodeDecodeError) as e:
        print("build_index 失败: %s" % e, file=sys.stderr)
        return 1

    if args.json:
        print(json.dumps({"ok": True, "root": str(root), **stats}, ensure_ascii=False))
    else:
        shard_desc = ", ".join("%s=%d" % (k, v) for k, v in stats["shards"].items())
        print("index.md rebuilt: %d agg entries; sources %d (%s%s); queries %d; "
              "contradictions %d; lineage %d; backlinks %d; wrote %d, unchanged %d%s"
              % (stats["agg_entries"], stats["sources"],
                 ("facet %s: " % stats["shard_facet"]) if stats["shard_facet"] else "",
                 shard_desc, stats["queries"], stats["contradictions"], stats["lineage"],
                 stats["backlinks"],
                 len(stats["written"]), len(stats["unchanged"]),
                 (", removed stale: %s" % ",".join(stats["removed"])) if stats["removed"] else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
